-- Add CAMBIO_ESTADO_PETICION to EventoTipo enum
ALTER TYPE "EventoTipo" ADD VALUE IF NOT EXISTS 'CAMBIO_ESTADO_PETICION';

-- Add CAMBIO_ESTADO_PETICION to WorkflowTrigger enum
ALTER TYPE "WorkflowTrigger" ADD VALUE IF NOT EXISTS 'CAMBIO_ESTADO_PETICION';

-- Add new condition field enum values for Estado Peticion
ALTER TYPE "WorkflowConditionField" ADD VALUE IF NOT EXISTS 'ESTADO_PETICION_ID';
ALTER TYPE "WorkflowConditionField" ADD VALUE IF NOT EXISTS 'ESTADO_PETICION_CODIGO';
ALTER TYPE "WorkflowConditionField" ADD VALUE IF NOT EXISTS 'ESTADO_PETICION_ANTERIOR_ID';
ALTER TYPE "WorkflowConditionField" ADD VALUE IF NOT EXISTS 'ESTADO_PETICION_NUEVO_ID';
ALTER TYPE "WorkflowConditionField" ADD VALUE IF NOT EXISTS 'ESTADO_PETICION_ANTERIOR_CODIGO';
ALTER TYPE "WorkflowConditionField" ADD VALUE IF NOT EXISTS 'ESTADO_PETICION_NUEVO_CODIGO';
